/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.ChargeCodes;
import java.util.List;

public interface ChargeCodesService {

	public ChargeCodes getOne(Integer chargeCode);

	public List<ChargeCodes> findAll();

	public Boolean delete(Integer chargeCode);

	public ChargeCodes create(ChargeCodes chargeCodes);

	public ChargeCodes update(ChargeCodes chargeCodes);

	public Boolean exist(ChargeCodes chargeCodes);
}
