/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.Contacts;
import java.util.List;

public interface ContactsService {

	public Contacts getOne(Integer contactId);

	public List<Contacts> findAll();

	public Boolean delete(Integer contactId);

	public Contacts create(Contacts contacts);

	public Contacts update(Contacts contacts);

	public Boolean exist(Contacts contacts);
}
