/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 17:51:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.Contacts;
import org.demo.repository.ContactsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class ContactsServiceImpl implements ContactsService {

	@Autowired
	private ContactsRepository contactsRepository;

	@Override
	public Contacts getOne(Integer contactId) {
		return contactsRepository.findById(contactId).get();
	}

	@Override
	public Boolean delete(Integer contactId) {
		if (contactsRepository.getOne(contactId) != null) {
			contactsRepository.deleteById(contactId);
			return true;
		}
		return false;
	}

	@Override
	public Contacts create(Contacts contacts) {
		return contactsRepository.save(contacts);
	}

	@Override
	public Contacts update(Contacts contactsToUpdate) {
						Contacts contacts = contactsRepository.getOne(contactsToUpdate.getContactId());
																						
				if(contactsToUpdate.getContactName() !=null) {
			
		}
				if(contactsToUpdate.getJobTitle() !=null) {
			
		}
				if(contactsToUpdate.getContactDetails() !=null) {
			
		}
				if(contactsToUpdate.getContactId() !=null) {
			
		}
				return contactsRepository.save(contacts);
	}

	@Override
	public Boolean exist(Contacts contacts) {
						return contactsRepository.existsById(contacts.getContactId());
																					}

	@Override
	public List<Contacts> findAll() {
		return contactsRepository.findAll();
	}

}


