/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.OutcomeCodes;
import org.demo.repository.OutcomeCodesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class OutcomeCodesServiceImpl implements OutcomeCodesService {

	@Autowired
	private OutcomeCodesRepository outcomeCodesRepository;

	@Override
	public OutcomeCodes getOne(Integer outcomeCodes) {
		return outcomeCodesRepository.findById(outcomeCodes).get();
	}

	@Override
	public Boolean delete(Integer outcomeCodes) {
		if (outcomeCodesRepository.getOne(outcomeCodes) != null) {
			outcomeCodesRepository.deleteById(outcomeCodes);
			return true;
		}
		return false;
	}

	@Override
	public OutcomeCodes create(OutcomeCodes outcomeCodes) {
		return outcomeCodesRepository.save(outcomeCodes);
	}

	@Override
	public OutcomeCodes update(OutcomeCodes outcomeCodesToUpdate) {
						OutcomeCodes outcomeCodes = outcomeCodesRepository.getOne(outcomeCodesToUpdate.getOutcomeCodes());
										
				if(outcomeCodesToUpdate.getOutcomeDescription() !=null) {
			
		}
				return outcomeCodesRepository.save(outcomeCodes);
	}

	@Override
	public Boolean exist(OutcomeCodes outcomeCodes) {
						return outcomeCodesRepository.existsById(outcomeCodes.getOutcomeCodes());
									}

	@Override
	public List<OutcomeCodes> findAll() {
		return outcomeCodesRepository.findAll();
	}

}


