/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.Problems;
import java.util.List;

public interface ProblemsService {

	public Problems getOne(Integer problemCode);

	public List<Problems> findAll();

	public Boolean delete(Integer problemCode);

	public Problems create(Problems problems);

	public Problems update(Problems problems);

	public Boolean exist(Problems problems);
}
