/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.StatusCode;
import java.util.List;

public interface StatusCodeService {

	public StatusCode getOne(Integer statusCode);

	public List<StatusCode> findAll();

	public Boolean delete(Integer statusCode);

	public StatusCode create(StatusCode statusCode);

	public StatusCode update(StatusCode statusCode);

	public Boolean exist(StatusCode statusCode);
}
