/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import org.demo.entity.Technicians;
import java.util.List;

public interface TechniciansService {

	public Technicians getOne(Integer technicianId);

	public List<Technicians> findAll();

	public Boolean delete(Integer technicianId);

	public Technicians create(Technicians technicians);

	public Technicians update(Technicians technicians);

	public Boolean exist(Technicians technicians);
}
