/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;



import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.Technicians;
import org.demo.repository.TechniciansRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class TechniciansServiceImpl implements TechniciansService {

	@Autowired
	private TechniciansRepository techniciansRepository;

	@Override
	public Technicians getOne(Integer technicianId) {
		return techniciansRepository.findById(technicianId).get();
	}

	@Override
	public Boolean delete(Integer technicianId) {
		if (techniciansRepository.getOne(technicianId) != null) {
			techniciansRepository.deleteById(technicianId);
			return true;
		}
		return false;
	}

	@Override
	public Technicians create(Technicians technicians) {
		return techniciansRepository.save(technicians);
	}

	@Override
	public Technicians update(Technicians techniciansToUpdate) {
						Technicians technicians = techniciansRepository.getOne(techniciansToUpdate.getTechnicianId());
										
				if(techniciansToUpdate.getTechnicianName() !=null) {
			
		}
				return techniciansRepository.save(technicians);
	}

	@Override
	public Boolean exist(Technicians technicians) {
						return techniciansRepository.existsById(technicians.getTechnicianId());
									}

	@Override
	public List<Technicians> findAll() {
		return techniciansRepository.findAll();
	}

}


