/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Actions search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ActionsCriteria {

    private String actionDescription; 
	// Constructor
	public ActionsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setActionDescription(String actionDescription) {this.actionDescription = actionDescription;}
	public String getActionDescription() {return this.actionDescription;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(actionDescription); 
        return sb.toString();
	}
}
