/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for ChargeCodes search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ChargeCodesCriteria {

    private String chargeDescription; 
	// Constructor
	public ChargeCodesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setChargeDescription(String chargeDescription) {this.chargeDescription = chargeDescription;}
	public String getChargeDescription() {return this.chargeDescription;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(chargeDescription); 
        return sb.toString();
	}
}
