/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 17:51:41 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Contacts search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ContactsCriteria {

    private String contactName; 
    private String jobTitle; 
    private String contactDetails; 
	// Constructor
	public ContactsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setContactName(String contactName) {this.contactName = contactName;}
	public String getContactName() {return this.contactName;}
	public void setJobTitle(String jobTitle) {this.jobTitle = jobTitle;}
	public String getJobTitle() {return this.jobTitle;}
	public void setContactDetails(String contactDetails) {this.contactDetails = contactDetails;}
	public String getContactDetails() {return this.contactDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(contactName); 
		sb.append("|"); 
		sb.append(jobTitle); 
		sb.append("|"); 
		sb.append(contactDetails); 
        return sb.toString();
	}
}
