/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Customers search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class CustomersCriteria {

    private String customerName; 
    private String customerAddress; 
    private String otherDetails; 
	// Constructor
	public CustomersCriteria() {
		// Needed empty constructor for serialization
	}

	public void setCustomerName(String customerName) {this.customerName = customerName;}
	public String getCustomerName() {return this.customerName;}
	public void setCustomerAddress(String customerAddress) {this.customerAddress = customerAddress;}
	public String getCustomerAddress() {return this.customerAddress;}
	public void setOtherDetails(String otherDetails) {this.otherDetails = otherDetails;}
	public String getOtherDetails() {return this.otherDetails;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(customerName); 
		sb.append("|"); 
		sb.append(customerAddress); 
		sb.append("|"); 
		sb.append(otherDetails); 
        return sb.toString();
	}
}
