/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for OutcomeCodes search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class OutcomeCodesCriteria {

    private String outcomeDescription; 
	// Constructor
	public OutcomeCodesCriteria() {
		// Needed empty constructor for serialization
	}

	public void setOutcomeDescription(String outcomeDescription) {this.outcomeDescription = outcomeDescription;}
	public String getOutcomeDescription() {return this.outcomeDescription;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(outcomeDescription); 
        return sb.toString();
	}
}
