/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Problems search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class ProblemsCriteria {

    private String problemDescription; 
	// Constructor
	public ProblemsCriteria() {
		// Needed empty constructor for serialization
	}

	public void setProblemDescription(String problemDescription) {this.problemDescription = problemDescription;}
	public String getProblemDescription() {return this.problemDescription;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(problemDescription); 
        return sb.toString();
	}
}
