/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for StatusCode search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class StatusCodeCriteria {

    private String statusDecription; 
	// Constructor
	public StatusCodeCriteria() {
		// Needed empty constructor for serialization
	}

	public void setStatusDecription(String statusDecription) {this.statusDecription = statusDecription;}
	public String getStatusDecription() {return this.statusDecription;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(statusDecription); 
        return sb.toString();
	}
}
