/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service.criteria;

/**
 * Criteria bean used for Technicians search.
 * @author Telosys (http://www.telosys.org/) version 3.0.0
 */
public class TechniciansCriteria {

    private String technicianName; 
	// Constructor
	public TechniciansCriteria() {
		// Needed empty constructor for serialization
	}

	public void setTechnicianName(String technicianName) {this.technicianName = technicianName;}
	public String getTechnicianName() {return this.technicianName;}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append(technicianName); 
        return sb.toString();
	}
}
