package org.demo.entity;
// Generated Oct 1, 2018 4:13:35 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChargeCodes generated by hbm2java
 */
@Entity
public class ChargeCodes implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer chargeCode;
	private String chargeDescription;
	private Set<ServiceRequestCalls> serviceRequestCallses = new HashSet<ServiceRequestCalls>(0);

	public ChargeCodes() {
	}

	public ChargeCodes(String chargeDescription, Set<ServiceRequestCalls> serviceRequestCallses) {
		this.chargeDescription = chargeDescription;
		this.serviceRequestCallses = serviceRequestCallses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Charge_Code", unique = true, nullable = false)
	public Integer getChargeCode() {
		return this.chargeCode;
	}

	public void setChargeCode(Integer chargeCode) {
		this.chargeCode = chargeCode;
	}

	@Column(name = "Charge_Description", length = 45)
	public String getChargeDescription() {
		return this.chargeDescription;
	}

	public void setChargeDescription(String chargeDescription) {
		this.chargeDescription = chargeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeCodes")
	public Set<ServiceRequestCalls> getServiceRequestCallses() {
		return this.serviceRequestCallses;
	}

	public void setServiceRequestCallses(Set<ServiceRequestCalls> serviceRequestCallses) {
		this.serviceRequestCallses = serviceRequestCallses;
	}

}
