package org.demo.entity;
// Generated Oct 1, 2018 4:13:35 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Problems generated by hbm2java
 */
@Entity
public class Problems implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer problemCode;
	private String problemDescription;
	private Set<ServiceRequestCalls> serviceRequestCallses = new HashSet<ServiceRequestCalls>(0);

	public Problems() {
	}

	public Problems(String problemDescription, Set<ServiceRequestCalls> serviceRequestCallses) {
		this.problemDescription = problemDescription;
		this.serviceRequestCallses = serviceRequestCallses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Problem_Code", unique = true, nullable = false)
	public Integer getProblemCode() {
		return this.problemCode;
	}

	public void setProblemCode(Integer problemCode) {
		this.problemCode = problemCode;
	}

	@Column(name = "Problem_Description", length = 45)
	public String getProblemDescription() {
		return this.problemDescription;
	}

	public void setProblemDescription(String problemDescription) {
		this.problemDescription = problemDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "problems")
	public Set<ServiceRequestCalls> getServiceRequestCallses() {
		return this.serviceRequestCallses;
	}

	public void setServiceRequestCallses(Set<ServiceRequestCalls> serviceRequestCallses) {
		this.serviceRequestCallses = serviceRequestCallses;
	}

}
