package org.demo.entity;
// Generated Oct 1, 2018 4:13:35 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceRequestActions generated by hbm2java
 */
@Entity
public class ServiceRequestActions implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer responseId;
	private Actions actions;
	private OutcomeCodes outcomeCodes;
	private ServiceRequestCalls serviceRequestCalls;
	private Technicians technicians;
	private Date responseDatetime;

	public ServiceRequestActions() {
	}

	public ServiceRequestActions(Actions actions, OutcomeCodes outcomeCodes, ServiceRequestCalls serviceRequestCalls,
			Technicians technicians) {
		this.actions = actions;
		this.outcomeCodes = outcomeCodes;
		this.serviceRequestCalls = serviceRequestCalls;
		this.technicians = technicians;
	}

	public ServiceRequestActions(Actions actions, OutcomeCodes outcomeCodes, ServiceRequestCalls serviceRequestCalls,
			Technicians technicians, Date responseDatetime) {
		this.actions = actions;
		this.outcomeCodes = outcomeCodes;
		this.serviceRequestCalls = serviceRequestCalls;
		this.technicians = technicians;
		this.responseDatetime = responseDatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Response_ID", unique = true, nullable = false)
	public Integer getResponseId() {
		return this.responseId;
	}

	public void setResponseId(Integer responseId) {
		this.responseId = responseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Action_Code", nullable = false)
	public Actions getActions() {
		return this.actions;
	}

	public void setActions(Actions actions) {
		this.actions = actions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Outcome_Code", nullable = false)
	public OutcomeCodes getOutcomeCodes() {
		return this.outcomeCodes;
	}

	public void setOutcomeCodes(OutcomeCodes outcomeCodes) {
		this.outcomeCodes = outcomeCodes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Call_ID", nullable = false)
	public ServiceRequestCalls getServiceRequestCalls() {
		return this.serviceRequestCalls;
	}

	public void setServiceRequestCalls(ServiceRequestCalls serviceRequestCalls) {
		this.serviceRequestCalls = serviceRequestCalls;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Technician_ID", nullable = false)
	public Technicians getTechnicians() {
		return this.technicians;
	}

	public void setTechnicians(Technicians technicians) {
		this.technicians = technicians;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Response_Datetime", length = 19)
	public Date getResponseDatetime() {
		return this.responseDatetime;
	}

	public void setResponseDatetime(Date responseDatetime) {
		this.responseDatetime = responseDatetime;
	}

}
