package org.demo.entity;
// Generated Oct 1, 2018 4:13:35 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceRequestCalls generated by hbm2java
 */
@Entity
public class ServiceRequestCalls implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer callId;
	private ChargeCodes chargeCodes;
	private Contacts contacts;
	private Problems problems;
	private StatusCode statusCode;
	private Date dateTimeOfCall;
	private String otherDetails;
	private Set<ServiceRequestActions> serviceRequestActionses = new HashSet<ServiceRequestActions>(0);

	public ServiceRequestCalls() {
	}

	public ServiceRequestCalls(ChargeCodes chargeCodes, Contacts contacts, Problems problems, StatusCode statusCode) {
		this.chargeCodes = chargeCodes;
		this.contacts = contacts;
		this.problems = problems;
		this.statusCode = statusCode;
	}

	public ServiceRequestCalls(ChargeCodes chargeCodes, Contacts contacts, Problems problems, StatusCode statusCode,
			Date dateTimeOfCall, String otherDetails, Set<ServiceRequestActions> serviceRequestActionses) {
		this.chargeCodes = chargeCodes;
		this.contacts = contacts;
		this.problems = problems;
		this.statusCode = statusCode;
		this.dateTimeOfCall = dateTimeOfCall;
		this.otherDetails = otherDetails;
		this.serviceRequestActionses = serviceRequestActionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Call_ID", unique = true, nullable = false)
	public Integer getCallId() {
		return this.callId;
	}

	public void setCallId(Integer callId) {
		this.callId = callId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Charge_Code", nullable = false)
	public ChargeCodes getChargeCodes() {
		return this.chargeCodes;
	}

	public void setChargeCodes(ChargeCodes chargeCodes) {
		this.chargeCodes = chargeCodes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Contact_ID", nullable = false)
	public Contacts getContacts() {
		return this.contacts;
	}

	public void setContacts(Contacts contacts) {
		this.contacts = contacts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Problem_Code", nullable = false)
	public Problems getProblems() {
		return this.problems;
	}

	public void setProblems(Problems problems) {
		this.problems = problems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status_Code", nullable = false)
	public StatusCode getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(StatusCode statusCode) {
		this.statusCode = statusCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date_Time_of_Call", length = 19)
	public Date getDateTimeOfCall() {
		return this.dateTimeOfCall;
	}

	public void setDateTimeOfCall(Date dateTimeOfCall) {
		this.dateTimeOfCall = dateTimeOfCall;
	}

	@Column(name = "Other_Details", length = 45)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceRequestCalls")
	public Set<ServiceRequestActions> getServiceRequestActionses() {
		return this.serviceRequestActionses;
	}

	public void setServiceRequestActionses(Set<ServiceRequestActions> serviceRequestActionses) {
		this.serviceRequestActionses = serviceRequestActionses;
	}

}
