package org.demo.entity;
// Generated Oct 1, 2018 4:13:35 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatusCode generated by hbm2java
 */
@Entity
public class StatusCode implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer statusCode;
	private String statusDecription;
	private Set<ServiceRequestCalls> serviceRequestCallses = new HashSet<ServiceRequestCalls>(0);

	public StatusCode() {
	}

	public StatusCode(String statusDecription, Set<ServiceRequestCalls> serviceRequestCallses) {
		this.statusDecription = statusDecription;
		this.serviceRequestCallses = serviceRequestCallses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Status_Code", unique = true, nullable = false)
	public Integer getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "Status_Decription", length = 45)
	public String getStatusDecription() {
		return this.statusDecription;
	}

	public void setStatusDecription(String statusDecription) {
		this.statusDecription = statusDecription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusCode")
	public Set<ServiceRequestCalls> getServiceRequestCallses() {
		return this.serviceRequestCallses;
	}

	public void setServiceRequestCallses(Set<ServiceRequestCalls> serviceRequestCallses) {
		this.serviceRequestCallses = serviceRequestCallses;
	}

}
